### ISSUE TITLE
Validation error on proper value

### ISSUE THREAD

**Issue by mareckii** [willthames/kubernetes-validate#4]
Hi according this issue: 
https://github.com/kubernetes/kubernetes/issues/24198
`  strategy:
    type: Recreate
    rollingUpdate: null`
is allowed but, output i get on validation say something different:
"resource definition validation error at spec.strategy.rollingUpdate: None is not of type u'object'"

**Comment by willthames** [comment]
I think it's a valid input to `kubectl apply` but it doesn't meet the kubernetes openapi schema that this project uses to generate the validations. 

I'm not sure the best approach to fix this - whether it's to just ignore null values (which is really the only way to unset something that was added by kubernetes rather than the user passing it in as in this example) or do something else

**Comment by willthames** [comment]
I realise this is an ancient issue but it looks like cutting over to a newer jsonschema version has fixed this for a whole bunch of types that are now optionally allowed to be null. 

kubernetes-validate v1.29.0 contains this change (with all the old versions (as far back as 1.22 which is the oldest version supported by kubernetes-validate now) updated as well)
